---
default:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
development:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  database: payroll-design-dev
  username: root
test:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  database: payroll-design-test
  username: root
production:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  database: payroll-design-prod
  username: root
  password: <%= ENV['STACKHERO_MYSQL_ROOT_PASSWORD'] %>
  host: <%= ENV['STACKHERO_MYSQL_HOST'] %>
