---
default:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
development:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  database: payroll-design-dev
  username: root
test:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  database: payroll-design-test
  username: root
staging:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  database: xxx
  username: xxx
  password: xxx
  host: xxx
production:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  database: xxx
  username: xxx
  password: xxx
  host: xxx
